name: publish

on:
    workflow_dispatch:
        inputs:
            repository-environment:
                description: "Publish environment"
                required: true
                default: "testpypi"
                type: choice
                options:
                    - testpypi
                    - pypi

jobs:
    build-and-publish:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install build backend
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build
              run: python -m build
            - name: Publish to TestPyPI
              if: inputs.repository-environment == 'testpypi'
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
            - name: Publish to PyPI
              if: inputs.repository-environment == 'pypi'
              uses: pypa/gh-action-pypi-publish@release/v1
